apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-rc
      labels:
        app: myapp-rc
    spec:
      containers:
        - name: nginx-container
          image: nginx